name: portfolio2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  page_transition: ^2.1.0
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/fonts/ # Add this line to include your font assets

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: ProtestStrike
      fonts:
        - asset: assets/fonts/ProtestStrike-Regular.ttf
