// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FM3CdqBG172s4TCKxOaBNbyQG08pm0U',
    appId: '1:219224384902:web:b0fed92a156a2d06a53807',
    messagingSenderId: '219224384902',
    projectId: 'portfolio-6efe4',
    authDomain: 'portfolio-6efe4.firebaseapp.com',
    storageBucket: 'portfolio-6efe4.appspot.com',
    measurementId: 'G-20QFBM7JJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0NddkYpU719lrZ5CzhHYPO6IUxeTeRpc',
    appId: '1:219224384902:android:20798f2386421144a53807',
    messagingSenderId: '219224384902',
    projectId: 'portfolio-6efe4',
    storageBucket: 'portfolio-6efe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8G72mSJfz_TtLnR2s6FjtSD2fDX7i_jw',
    appId: '1:219224384902:ios:c52a8078a669e980a53807',
    messagingSenderId: '219224384902',
    projectId: 'portfolio-6efe4',
    storageBucket: 'portfolio-6efe4.appspot.com',
    iosBundleId: 'com.example.portfolio2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8G72mSJfz_TtLnR2s6FjtSD2fDX7i_jw',
    appId: '1:219224384902:ios:c52a8078a669e980a53807',
    messagingSenderId: '219224384902',
    projectId: 'portfolio-6efe4',
    storageBucket: 'portfolio-6efe4.appspot.com',
    iosBundleId: 'com.example.portfolio2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4FM3CdqBG172s4TCKxOaBNbyQG08pm0U',
    appId: '1:219224384902:web:032daeb5cb6c1336a53807',
    messagingSenderId: '219224384902',
    projectId: 'portfolio-6efe4',
    authDomain: 'portfolio-6efe4.firebaseapp.com',
    storageBucket: 'portfolio-6efe4.appspot.com',
    measurementId: 'G-E4N4NTZ5EY',
  );

}